package Singleplayer;



import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.net.UnknownHostException;

/*  Assignment for Network Programming S1,2019
 *  @author: Hao Wang (s3690173)
 *  A.1 Single player version
 *  The client connects to the server and guess the 
 *  number which generated by the server from 0-9,
 *  and the client have 4 chances to guess. The game
 *  will end when the client running out the chances or 
 *  make the correct guess.
 *  
 *  This is the Client end.
 */
public class SingleClient {
	public static void main(String[] args) throws IOException {
		Socket socket = null;
		BufferedReader reader;
		DataOutputStream out = null;
		DataInputStream in = null;
		boolean success = false;
		int times = 4;
		try {
			System.out.print("Please input the server address:");
			BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
			String serverAddress = br.readLine();
			socket = new Socket(serverAddress, 61099);
			reader = new BufferedReader(new InputStreamReader(System.in));
			out = new DataOutputStream(socket.getOutputStream());
			in = new DataInputStream(new BufferedInputStream(socket.getInputStream()));
			while (!success) {
				out.writeInt(Integer.parseInt(reader.readLine()));
				out.flush();
				success = in.readBoolean();
				System.out.println(in.readUTF());
				times--;
				if (times == 0)
					break;
			}
		} catch (UnknownHostException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			in.close();
			out.close();
			socket.close();
		}
	}
}
